### PR TITLE
Make file

### PR DESCRIPTION
**Pull request by hrshdhgd**
Adresses https://github.com/mapping-commons/disease-mappings/issues/9

 - [x] Get ontology owl files
 - [x] `robot merge all-owl-files`
 - [x] Get corresponding SSSOM mappings
 - [x] Aggregate all mapping files
 - [x] Generate `all_mappings_ptables.tsv`
 - [x] Create `prefix_map.yaml`
 - [x] Run Boomer

### CODE REVIEW

**Comment by hrshdhgd** [comment]
@matentzn ; @cmungall : First stab at this.

**Comment by matentzn** [comment]
This looks fantastic so far!

**Comment by matentzn** [comment]
From meeting:

- consider exhaustive-search-limit
- Greedy search: take mappings in some order - that's why you do a bunch of runs (`runs`)
- Install boomer from github
- Think about the best way to communicate that a previous equivalent mapping
- Do not generate a PNG for singleton png (see how to exclude: https://stackoverflow.com/questions/7402205/remove-item-from-a-makefile-variable)

**Comment by matentzn** [comment]
Can we merge this and iterate? I want to add some things in parallel to the setup..

**Comment by hrshdhgd** [comment]
Done!

**Comment by matentzn** [comment]
thx

**Pull request merged**
